language: node_js
node_js:
  - "0.10"
script: "npm run coverage"
env:
  - CODECLIMATE_REPO_TOKEN=dfeabb7386cbb28747fff2d2c6fa68857fdd989a900bb8957625ab6b9ba10679
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info